In [2]:
import numpy as np

In [4]:
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [5]:
arr1[arr1<3]

array([0, 1, 2])

In [6]:
len(arr1[arr1<3])

3

In [7]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.random.randint(low=30, high=100, size=(7,4)) #low, high  = >기준점 
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[88 85 78 41]
 [91 73 79 42]
 [97 53 47 31]
 [59 99 42 42]
 [47 35 31 35]
 [76 80 62 77]
 [76 50 91 93]]


In [8]:
names =="Bob"

array([ True, False, False,  True, False, False, False])

In [9]:
names[names=="Bob"]

array(['Bob', 'Bob'], dtype='<U4')

In [10]:
len(names[names=="Bob"])

2

In [11]:
data[names=="Bob"]

array([[88, 85, 78, 41],
       [59, 99, 42, 42]])

In [14]:
data[[0,3]] #?___?

array([[88, 85, 78, 41],
       [59, 99, 42, 42]])

In [16]:
data[names=="Bob", :2]

array([[88, 85],
       [59, 99]])

In [20]:
data[names=="Bob"][0]

array([88, 85, 78, 41])

In [25]:
data[(names=="Bob") | (names=="Will")] #() is nescessary

array([[88, 85, 78, 41],
       [97, 53, 47, 31],
       [59, 99, 42, 42],
       [47, 35, 31, 35]])

In [26]:
data[(names=="Bob") | (names=="Will"), :2]

array([[88, 85],
       [97, 53],
       [59, 99],
       [47, 35]])

# 90점 이상인 학생이름 추출하기!! >> 데이터 변경  후 진행

In [28]:
data

array([[88, 85, 78, 41],
       [91, 73, 79, 42],
       [97, 53, 47, 31],
       [59, 99, 42, 42],
       [47, 35, 31, 35],
       [76, 80, 62, 77],
       [76, 50, 91, 93]])

In [32]:
data[data<90] = 0 #순서 중요!! >> data<90 ->data>=90

In [33]:
data #단점 > 국영수사의 과목기준이 같아야 가능. 

array([[ 0,  0,  0,  0],
       [91,  0,  0,  0],
       [97,  0,  0,  0],
       [ 0, 99,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 91, 93]])

In [35]:
data[data>=90] = 1
data

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 1]])

In [36]:
np.where(data>0) #값이 어디에 있어요!!? = where

(array([1, 2, 3, 6, 6], dtype=int64), array([0, 0, 1, 2, 3], dtype=int64))

In [37]:
np.where(data>0)[0]

array([1, 2, 3, 6, 6], dtype=int64)

In [38]:
np.unique(np.where(data>0)[0])

array([1, 2, 3, 6], dtype=int64)

In [39]:
names[np.unique(np.where(data>0)[0])]

array(['Joe', 'Will', 'Bob', 'Joe'], dtype='<U4')

# 모양변경 : shqpe =>reshape

In [40]:
arr =np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr = arr.reshape((4,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

# 기본적인 수학적인 함수들 => max, min

# sort 기능