In [5]:
import numpy as np #약어는 약어만!!, mixing is not allowed 

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
a = [1,2,3,4,5] #메모리상 흩어져 저장될 수 있다. in original Python
a

[1, 2, 3, 4, 5]

In [21]:
a = [16,17,18,19,20]
b=[]
for i in range(0, len(a)) :
    b.append(a[i]+15)
print(b)

[31, 32, 33, 34, 35]


In [23]:
a = np.array(a)
print(a)

[16 17 18 19 20]


In [25]:
a+15 #일괄연산

array([31, 32, 33, 34, 35])

In [27]:
a. = [1,2,3,4,5,6,7,8,9,10]
b. = [11,12,13,14,15,16,17,18,19,20]
c= []
for i in range(0,len(a)) :
    c.append(a[i]+b[i])
print(c)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


# array와 list의 '+' 연산이 다르다!!!

In [78]:
a+b #결과 >>[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

SyntaxError: invalid syntax (<ipython-input-78-0efcabfba17f>, line 1)

In [33]:
arr_a=np.array(a)
arr_b=np.array(b)
c = arr_a + arr_b
print(c)

[12 14 16 18 20 22 24 26 28 30]


In [38]:
print(c.ndim) #차원
print(c.shape) #받은 데이터의 수를 체크하기 위해서!!!
print(c.dtype)

1
(10,)
int32


# 차원 생성과정

In [45]:
data2 = [[1,2,3,4], [5,6,7,8,[9,10,11]]] #구조, 모양이 일치하지 않으면, 차원으로 돌아가는게 아니라 list로 들어간다. 
arr2=np.array(data2)
arr2

array([list([1, 2, 3, 4]), list([5, 6, 7, 8, [9, 10, 11]])], dtype=object)

In [48]:
data3 = [[1,2,3] , [4,5,6]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

1
(2,)
object


# 어레이의 원소타입 변경 부분


In [50]:
arr3 = np.array([1,2,3], dtype=np.string_)
arr3

array([b'1', b'2', b'3'], dtype='|S1')

# array(numpy) 와 list(original py)의 속도비교 =>해당 패키지가 있는지 찾아봐야


In [52]:

# 물론 조건 및 여러 상황에 따라서 조금 다를 수 있으니 참고!

# 01) 아래는 두 개의 리스트에서 각기 리스트의 합을 구하는 경우
# ( 코드 상 차이가 발생하는 부분들 : range, 리스트에서 +는 리스트 연결이나, numpy에서는 각기 원소들의 합
# 따라서 동일한 역할을 위해서는 리스트에서는for가 필요함

import time
size_vector = 100000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print ("python list Load Time : " + str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print ("python list for loop : " + str(t4- t3))
    
    print (" Python List Total :" + str(t4 - t1))

    
def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array1 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print ("numpy array1 for loop : " + str(t4- t3))

    print (" numpy array1 Total :" + str(t4 - t1))

def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array2 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i] #array와 list 짬뽕
    t4 = time.time()
    print ("numpy array2 for loop : " + str(t4- t3))
    print (" numpy array2 Total :" + str(t4 - t1))

print (" size_vector : 100000")
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")

print (" size_vector : 100")
size_vector = 100
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")


#  샘플 결과 
# -->기본적으로 일반적인 list로 생성하는 것이 array로 생성하는 것에 비해서 많은 속도가 소욧된다.
# --> numpy의 백터 연산이 기본적인 for에서 append보다 속도가 빠른 것을 볼 수 있음.
# --> 동잉한 for에 대해서도 상당히 속도가 빠른 것을 볼 수 있다. 
# --> 작은 숫자에서는 큰 차이가 없거나 경우에 따라서 List가 빠를 수도 있음.

 size_vector : 100000
python list Load Time : 0.0
python list for loop : 0.024932861328125
 Python List Total :0.024932861328125
numpy array1 Load Time : 0.0
numpy array1 for loop : 0.0
 numpy array1 Total :0.0
numpy array2 Load Time : 0.000997304916381836
numpy array2 for loop : 0.032962799072265625
 numpy array2 Total :0.03396010398864746
------------------------------
 size_vector : 100
python list Load Time : 0.0
python list for loop : 0.0009472370147705078
 Python List Total :0.0009472370147705078
numpy array1 Load Time : 0.0
numpy array1 for loop : 0.0
 numpy array1 Total :0.0
numpy array2 Load Time : 0.0
numpy array2 for loop : 0.0
 numpy array2 Total :0.0
------------------------------


In [53]:
# 02) 속도 비교
# 제곱 결과들

def square_list0(N):
    squares = []
    for n in range(N):
        squares = squares + [n**2]
    return squares


def square_list1(N):
    squares = []
    for n in range(N):
        # 일반적으로 생성해서 더하는 방법
        squares += [n**2]
    return squares
    

def square_list2(N):
    squares = []
    for n in range(N):
        # append 라고 이미 정의된 메소드 이용하는 방법
        squares.append(n**2)
    return squares
    

def square_list3(N):
    # 동일한 방법이나 벡터연산으로 처리
    return [n**2 for n in range(N)] 
#리스트 => 값을 모을 거에요 
#n**2 값을 모을거에요
#그 N은 반복문에 있어요 

def square_array(N):
    # Vectorize the entire operation.
    #from numpy import arange
    #return arange(N)**2
    return np.arange(N)**2 #numpy => 원소 개별에 접근한다. 


n = 100
print("Number :" ,n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print ("List0-Try : ",t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print ("List1-Try : ",t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print ("List2-Try : ",t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print ("List3-Try : ",t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print ("Array-Try : ",t2-t1)
print ("---------------")

n = 100000
print("Number :", n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print ("List0-Try : ",t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print ("List1-Try : ",t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print ("List2-Try : ",t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print ("List3-Try : ",t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print ("Array-Try : ",t2-t1)



# 결과 
# ---> 리스트를 사용할 것이라면 그래도 내부적으로 정의된 append가 빠르며
# ---> 리스트를 사용할 때 이보다더 더 빠르게 사용하려면 "벡터연산"으로 코드를 변경할 것
# ---> 이보다도 numpy가 더 빠르다. 특히 n이 작으면 차이가 별로 없으나, 커질수록 많이 차이가 남!!!

Number : 100
List0-Try :  0.0
List1-Try :  0.0
List2-Try :  0.0
List3-Try :  0.0
Array-Try :  0.0
---------------
Number : 100000
List0-Try :  11.408506393432617
List1-Try :  0.03091740608215332
List2-Try :  0.028922557830810547
List3-Try :  0.03390955924987793
Array-Try :  0.0


# python range / numpy np.arrange 기능 유사

# astype : 배열 이미 안에 있는 것의 자료형 변경

# 리스트와 array 색인 비슷

In [55]:
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [56]:
print(list1[0])
print(arr1[0])

1
1


In [59]:
print(list1[1:3])
print(arr1[1:3])
print(list1[:])
print(arr1[:])
print(list1[::2])
print(arr1[::2]) 

[2, 3]
[2 3]
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[1, 3, 5]
[1 3 5]


In [65]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [4]:
a= np.arange(0,51,10)[:,np.newaxis] + np.arange(0,6,1) #가로를 세로로 바꿔주는거

NameError: name 'np' is not defined

In [72]:
a[0][3:5]

array([3, 4])

In [73]:
a[0, 3:5]

array([3, 4])

In [2]:
a[:, 2][:,np.newaxis]

NameError: name 'a' is not defined

In [3]:
a[2::2, 0::2]

NameError: name 'a' is not defined

In [82]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

# Boolean Indexing

In [87]:
arr1 = np.arange(10)
print(arr1)
print(arr1<5) #모든 값에 대해서 5보다 작아???
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
